name: ddo-assimilation
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - click
  - pillow
  - scipy
  - pytorch
  - psutil
  - requests
  - tqdm
  - imageio
  - hydra-core
  - wandb
  - pip:
      - imageio-ffmpeg
      - pyspng
      - git+https://gitlab.eumetsat.int/eumetlab/data-services/eumdac.git
      - git+https://github.com/brightbandtech/nnja-ai.git
      - matplotlib
      - python-dotenv
      - xarray[complete]
      - dask
      - geopy
      - pyproj
      - gcsfs
      # neural operators
      - git+https://github.com/neuraloperator/neuraloperator
      # eumstat data access
      - git+https://gitlab.eumetsat.int/eumetlab/data-services/eumdac.git
      - matplotlib
      - noise
      - joblib
      - jstyleson
      - torchvision
      - einops
      - omegaconf
      - logger
