name: edm-operator
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - click
  - pillow
  - scipy
  - pytorch
  - psutil
  - requests
  - tqdm
  - imageio
  - pip:
      - imageio-ffmpeg
      - pyspng
      - git+https://gitlab.eumetsat.int/eumetlab/data-services/eumdac.git
      - matplotlib
      - python-dotenv
      - xarray[complete]
      - dask
      - geopy
      - pyproj
      - gcsfs
