_target_: training.collate.CompositeCollate
collate_fns:
  - _target_: training.collate.MakeConditional # add a None for conditioning
  - _target_: training.collate.CollateIrregular
    strategy: resample
    max_samples: 128
