_target_: data.synthetic.SpatioTemporalSlice
entire_simulation: 2D_NS_Re40.npy

# the size of the sampled windows
spatial_window: [32, 32]
temporal_window: 16

# sample a mask to make the data irregular
mask_sampler:
  _target_: data.synthetic.perlin_mask_sampler
  _partial_: true
  scale: 10.0
  octaves: 1
  persistence: 0.5
  lacunarity: 2.0
  cutoff: 0.0
  seed: 0

total_count: 16
