defaults:
  - dataset: regional_ns_irregular
  - score_net: gino
  - preconditioner: edm
  - sampler: rbf_sampler
  - loss: edm_loss
  - optimizer: adam
  - augment_pipe: default
  - wandb: enabled # set to disabled for local runs
  - _self_

# arguments for the dataloader
dataloader_args:
  num_workers: 1
  pin_memory: True
  prefetch_factor: 2

seed: 42 # Hitchhiker's Guide to the Galaxy
base_learning_rate: 10e-4
batch_size: 512
batch_gpu: 512
total_kimg: 200000
ema_halflife_kimg: 500
ema_rampup_ratio: 0.05
lr_rampup_kimg: 10000
loss_scaling: 1
kimg_per_tick: 50
snapshot_ticks: 50
state_dump_ticks: 500
resume_pkl: null
resume_state_dump: null
resume_kimg: 0
cudnn_benchmark: True
device: cuda
